@PORT = 3000

@HOST = http://localhost:{{PORT}}

### AUTORES: Obtención y creación
GET {{HOST}}/api/autores
###
GET {{HOST}}/api/autores/2
###
POST {{HOST}}/api/autores
Content-Type: application/json

{
    "nombre": "Juan Perez",
    "email": "juanperez@gmail.com",
    "imagen": "http://imagen/profile1.com"

}

### AUTORES: Actualización y borrado
###
PUT {{HOST}}/api/autores/5
Content-Type: application/json

{
    "nombre": "Carla Rueda",
    "email": "carlarueda@gmail.com",
    "imagen": "http://imagen/profile.com"

}

###
DELETE {{HOST}}/api/autores/7

### ------------------------------------------------------- ###

### POSTS: Obtención y Creación
GET {{HOST}}/api/posts
###
GET {{HOST}}/api/posts/1
Content-Type: application/json
###
GET {{HOST}}/api/posts/2
Content-Type: application/json
###
POST {{HOST}}/api/posts
Content-Type: application/json

{
    "titulo": "title09",
    "descripcion": "descripcion",
    "fecha_creacion": "fecha de creacion",
    "categoria": "categoria",
    "autor": "autor",
    "FK_autor_id": 2
}