@PORT = 3000

@HOST = http://localhost:{{PORT}}

### AUTORES: Obtención y creación
GET {{HOST}}/api/autores
###
GET {{HOST}}/api/autores/2
###
POST {{HOST}}/api/autores
Content-Type: application/json

{
    "nombre": "Pablo Correa",
    "email": "pablocorrea@gmail.com",
    "imagen": "http://imagen/profile11.com"

}

### AUTORES: Actualización y borrado
###
PUT {{HOST}}/api/autores/5
Content-Type: application/json

{
    "nombre": "Sofia Castro",
    "email": "sofiacastro-NEW@gmail.com",
    "imagen": "http://imagen/profile5-NEW.com"

}

###
DELETE {{HOST}}/api/autores/7

### ------------------------------------------------------- ###

### POSTS: Obtención y Creación
GET {{HOST}}/api/posts
###
GET {{HOST}}/api/posts/3
###
GET {{HOST}}/api/posts/autor/2
###
POST {{HOST}}/api/posts
Content-Type: application/json

{
    "titulo": "La Influencia del Arte en la Cultura Popular",
    "descripcion": "Analizando cómo las expresiones artísticas moldean las tendencias modernas",
    "categoria": "Arte",
    "FK_autor_id": 11
}

###
PUT {{HOST}}/api/posts/5
Content-Type: application/json

{
    "titulo": "Moda y Medio Ambiente",
    "descripcion": "Explorando el impacto de la moda rápida en el medio ambiente.",
    "categoria": "Moda"
}

###
DELETE {{HOST}}/api/posts/10